// Generated by https://quicktype.io

export interface CitiesColombia {
    data: CitiesColombiaData;
    meta: Meta;
}

export interface CitiesColombiaData {
    id:         number;
    attributes: DataAttributes;
}

export interface DataAttributes {
    id_subcategory: string;
    uuid:           string;
    name:           string;
    description:    string;
    deleted:        boolean;
    created:        string;
    updated:        string;
    createdAt:      string;
    updatedAt:      string;
    publishedAt:    string;
    locale:         string;
    data:           null;
    places:         Places;
}

export interface Places {
    data: PlacesDatum[];
}

export interface PlacesDatum {
    id:         number;
    attributes: PurpleAttributes;
}

export interface PurpleAttributes {
    id_place:    string;
    uuid:        string;
    type:        string;
    name:        string;
    description: null;
    location:    Location;
    data:        AttributesData;
    deleted:     null;
    created:     null;
    updated:     null;
    tags:        null;
    createdAt:   string;
    updatedAt:   string;
    publishedAt: string;
    locale:      string;
    media:       Media;
}

export interface AttributesData {
    geoJSON: string;
}

export interface Location {
    ciudad:   string;
    latitud:  string;
    longitud: string;
}

export interface Media {
    data: MediaDatum[];
}

export interface MediaDatum {
    id:         number;
    attributes: FluffyAttributes;
}

export interface FluffyAttributes {
    name:              string;
    alternativeText:   null;
    caption:           null;
    width:             number;
    height:            number;
    formats:           Formats;
    hash:              string;
    ext:               string;
    mime:              string;
    size:              number;
    url:               string;
    previewUrl:        null;
    provider:          string;
    provider_metadata: null;
    createdAt:         string;
    updatedAt:         string;
}

export interface Formats {
    thumbnail: Thumbnail;
}

export interface Thumbnail {
    name:   string;
    hash:   string;
    ext:    string;
    mime:   string;
    path:   null;
    width:  number;
    height: number;
    size:   number;
    url:    string;
}

export interface Meta {
}
