// Generated by https://quicktype.io

export interface DepartmentColombia {
    data: DepartmentColombiaData;
    meta: Meta;
}

export interface DepartmentColombiaData {
    id:         number;
    attributes: DataAttributes;
}

export interface DataAttributes {
    id_subcategory: string;
    uuid:           string;
    name:           string;
    description:    null;
    deleted:        boolean;
    created:        string;
    updated:        string;
    createdAt:      string;
    updatedAt:      string;
    publishedAt:    string;
    locale:         Locale;
    data:           null;
    places:         Places;
}

export enum Locale {
    EsCO = "es-CO",
}

export interface Places {
    data: PlacesDatum[];
}

export interface PlacesDatum {
    id:         number;
    attributes: PurpleAttributes;
}

export interface PurpleAttributes {
    id_place:    string;
    uuid:        string;
    type:        string;
    name:        string;
    description: null | string;
    location:    Location;
    data:        AttributesData;
    deleted:     boolean | null;
    created:     null | string;
    updated:     null | string;
    tags:        null;
    createdAt:   string;
    updatedAt:   string;
    publishedAt: string;
    locale:      Locale;
    media:       Media;
}

export interface AttributesData {
    geoJSON: string;
}

export interface Location {
    departamento?:  string;
    latitud:        string;
    longitud:       string;
    departamentos?: string;
    ciudad?:        string;
}

export interface Media {
    data: MediaDatum[];
}

export interface MediaDatum {
    id:         number;
    attributes: FluffyAttributes;
}

export interface FluffyAttributes {
    name:              string;
    alternativeText:   null;
    caption:           null;
    width:             number;
    height:            number;
    formats:           Formats;
    hash:              string;
    ext:               EXT;
    mime:              MIME;
    size:              number;
    url:               string;
    previewUrl:        null;
    provider:          Provider;
    provider_metadata: null;
    createdAt:         string;
    updatedAt:         string;
}

export enum EXT {
    GIF = ".gif",
    Jpg = ".jpg",
    PNG = ".png",
}

export interface Formats {
    thumbnail: Large;
    medium?:   Large;
    small?:    Large;
    large?:    Large;
}

export interface Large {
    name:   string;
    hash:   string;
    ext:    EXT;
    mime:   MIME;
    path:   null;
    width:  number;
    height: number;
    size:   number;
    url:    string;
}

export enum MIME {
    ImageGIF = "image/gif",
    ImageJPEG = "image/jpeg",
    ImagePNG = "image/png",
}

export enum Provider {
    Local = "local",
}

export interface Meta {
}
