// Generated by https://quicktype.io

export interface FilterTourism {
    data: FilterTourismDatum[];
    meta: Meta;
}

export interface FilterTourismDatum {
    id:         number;
    attributes: PurpleAttributes;
}

export interface PurpleAttributes {
    id_subcategory: string;
    uuid:           string;
    name:           string;
    description:    null;
    deleted:        boolean;
    created:        string;
    updated:        string;
    createdAt:      string;
    updatedAt:      string;
    publishedAt:    string;
    locale:         Locale;
    data:           null;
    inventory:      Inventory;
    category:       Category;
    media:          Localizations;
    products:       Localizations;
    services:       Localizations;
    posts:          Localizations;
    places:         Localizations;
    points:         Localizations;
    seo:            any[];
    metasocial:     any[];
    localizations:  Localizations;
}

export interface Category {
    data: CategoryData;
}

export interface CategoryData {
    id:         number;
    attributes: FluffyAttributes;
}

export interface FluffyAttributes {
    id_category: string;
    name:        PurpleName;
    description: Description;
    deleted:     boolean;
    created:     string;
    updated:     string;
    createdAt:   string;
    updatedAt:   string;
    publishedAt: string;
    locale:      Locale;
    data:        null;
}

export enum Description {
    ContieneTodasLasCategoriasDePuntosTuristicos = "contiene todas las categorias de puntos turisticos ",
}

export enum Locale {
    EsCO = "es-CO",
}

export enum PurpleName {
    PuntosTuristicosRunalotus = "Puntos turisticos runalotus",
}

export interface Inventory {
    data: InventoryData;
}

export interface InventoryData {
    id:         number;
    attributes: TentacledAttributes;
}

export interface TentacledAttributes {
    id_inventory: string;
    uuid:         UUID;
    createdAt:    string;
    updatedAt:    string;
    publishedAt:  string;
    name:         FluffyName;
}

export enum FluffyName {
    InventoryMaribel = "inventory-maribel",
}

export enum UUID {
    Inventory1 = "inventory-1",
}

export interface Localizations {
    data: LocalizationsDatum[];
}

export interface LocalizationsDatum {
    id:         number;
    attributes: StickyAttributes;
}

export interface StickyAttributes {
    name:               string;
    alternativeText?:   null;
    caption?:           null;
    width?:             number;
    height?:            number;
    formats?:           Formats;
    hash?:              string;
    ext?:               EXT;
    mime?:              MIME;
    size?:              number;
    url?:               string;
    previewUrl?:        null;
    provider?:          Provider;
    provider_metadata?: null;
    createdAt:          string;
    updatedAt:          string;
    id_point?:          string;
    uuid?:              string;
    description?:       null | string;
    location?:          Location;
    state?:             null | string;
    data?:              null;
    deleted?:           boolean;
    created?:           null | string;
    updated?:           null | string;
    tags?:              null | string;
    publishedAt?:       string;
    locale?:            Locale;
    gMapsPoint?:        null;
}

export enum EXT {
    Webp = ".webp",
}

export interface Formats {
    thumbnail?: Thumbnail;
}

export interface Thumbnail {
    name:   string;
    hash:   string;
    ext:    EXT;
    mime:   MIME;
    path:   null;
    width:  number;
    height: number;
    size:   number;
    url:    string;
}

export enum MIME {
    ImageWebp = "image/webp",
}

export interface Location {
    nombre:       string;
    ubicacion:    string;
    descripcion:  string;
    departamento: Departamento;
    clima:        string;
    latitud:      number;
    longitud:     number;
    icon:         string;
    type:         string;
}

export enum Departamento {
    Amazonas = "Amazonas",
    Antioquia = "Antioquia",
    Cundinamarca = "Cundinamarca",
    Huila = "Huila",
    LaGuajira = "La Guajira",
}

export enum Provider {
    Local = "local",
}

export interface Meta {
    pagination: Pagination;
}

export interface Pagination {
    page:      number;
    pageSize:  number;
    pageCount: number;
    total:     number;
}
